import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { MdNotificationsActive } from 'react-icons/md';
import Link from 'next/link';

export default function Home() {
  return (
    <div className={styles.page}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            <code className={styles.code}>
              This was built by Brian Reisman using:
            </code>
          </p>
          <ul className={styles.techList}>
            <li>NextJS</li>
            <li>SQLite database</li>
            <li>Prisma (ORM)</li>
            <li>styled-components</li>
          </ul>
          <Link href="/notifications">
            <MdNotificationsActive className={styles.notificationIcon} />
          </Link>
        </div>
      </main>
    </div>
  );
}
