import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '../styles/Home.module.css';
import { MdNotificationsActive } from 'react-icons/md';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            <code className={styles.code}>
              This was built by Brian Reisman using:
            </code>
          </p>
          <ul>
            <li>NextJS</li>
            <li>SQLite database</li>
            <li>Prisma (ORM)</li>
            <li>styled-components</li>
          </ul>
          <div>
            <Link href="/notifications">
              <MdNotificationsActive
                style={{
                  color: 'red',
                  height: '2rem',
                  width: '100%',
                  border: '1px solid blue',
                }}
              />
            </Link>
          </div>
        </div>
      </main>
    </>
  );
}
